global:  
  scrape_interval:     5s
  evaluation_interval: 5s
 
scrape_configs:  
  - job_name: 'todo-app'

    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']