# curl -X GET http://localhost:8181/persons/search/findByEmailIgnoreCase?email=mark@example.com -u admin@example.com:admin
GET http://localhost:8181/persons/search/findByEmailIgnoreCase?email=mark@example.com
Authorization: Basic admin@example.com admin

###

GET http://localhost:8181/persons/search/findByEmailIgnoreCase?email=mark@example.com
Accept: */*
Cache-Control: no-cache

###

